#disabled the output of hydra
defaults:
  - override hydra/job_logging: none
hydra:
  run:
    dir: .
  output_subdir: null

#Use CUDA (default: true)
cuda: true

#Use dummy train/val sets (default: false)
dummy: false

#Number of data loader worker threads (default: 1)
num_workers: 1

#Folder to write logs into
log_dir: ../lyricsalignment_mtl_output_csd/tensorboard_logs

#Dataset
dataset:
  name: csd
  n_phone_class: 34
  n_pitch_class: 47
  phone_blank: 33
  phones: [ 'u', 'k', 'kk', 'h', 'd', 'ch', 's', 'a', 'b', 'ui', 'r', 'tt', 'eu', 'n', 'ng', 'y', 'ss', 'i', 'eo', 'jj', 'w', 'oe', 'm', 'p', 'e', 'o', 'l', 'ae', 't', 'g', 'pp', 'j', ' ' ]
  #Dataset path
  dataset_dir: /home/ryan/dataset/csd
  #Where all the separated vocals are stored.
  sepa_dir: /home/ryan/dataset/csd/audio
  #Dataset path
  hdf_dir: /home/ryan/dataset/csd/hdf

#Folder to write checkpoints into
checkpoint_dir: ../lyricsalignment_mtl_output_csd/checkpoints

#"baseline" or "MTL"
model: MTL

#Reload a previously trained model (whole task model)
load_model: null

#Learning rate (default: 1e-4)
lr: 0.0001

#Batch size
batch_size: 64

#Sampling rate
sr: 22050

#Input sample
input_sample: 123904

#num of cnn layers
cnn_layers: 1

#dimension of rnn layers
rnn_dim: 256

#weight of voc loss
loss_w: 0.5